# Allows you to add config files
# apmConfig:
#   apm-server.yml: |
#     apm-server:
#       host: "0.0.0.0:8200"
#     queue: {}
#     output.elasticsearch:
#       hosts: ["http://elasticsearch-master:9200"]
#       username: "${ELASTICSEARCH_USERNAME}"
#       password: "${ELASTICSEARCH_PASSWORD}"
#       ## If SSL is enabled
#       # protocol: https
#       # ssl.certificate_authorities:
#       #  - /usr/share/apm-server/config/certs/elastic-ca.pem
# replicas: 1

# extraEnvs:
#   - name: "ELASTICSEARCH_USERNAME"
#     valueFrom:
#       secretKeyRef:
#         name: elasticsearch-master-credentials
#         key: username
#   - name: "ELASTICSEARCH_PASSWORD"
#     valueFrom:
#       secretKeyRef:
#         name: elasticsearch-master-credentials
#         key: password